# Generated by Django 4.1.7 on 2023-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tweet_media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_media/'),
        ),
    ]
