# Generated by Django 4.1.7 on 2023-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweet_controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_comments",
                to="tweet_controller.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="replay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_replay",
                to="tweet_controller.tweet",
            ),
        ),
    ]
