# Generated by Django 4.1.7 on 2023-04-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweet_controller", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="replay",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="like",
        ),
        migrations.AddField(
            model_name="media",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="tweet_media/"),
        ),
        migrations.AlterField(
            model_name="media",
            name="media",
            field=models.ImageField(blank=True, null=True, upload_to="tweet_media/"),
        ),
        migrations.AlterField(
            model_name="media",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_for_tweet",
                to="tweet_controller.tweet",
            ),
        ),
    ]
