# Generated by Django 4.1.7 on 2023-05-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet_controller", "0002_alter_tweet_comment_alter_tweet_replay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
