# Generated by Django 4.1.7 on 2023-05-04 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet_controller", "0005_alter_bookmarks_tweet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarks",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmark_tweet",
                to="tweet_controller.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="bookmarks",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmark_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
