# Generated by Django 4.1.7 on 2023-04-09 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet_controller", "0005_rename_media_media_image_alter_media_tweet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="image",
        ),
        migrations.RemoveField(
            model_name="media",
            name="video",
        ),
        migrations.AddField(
            model_name="media",
            name="file",
            field=models.FileField(default=0, upload_to="tweet_media/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="media",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="tweet_controller.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
