# Generated by Django 4.1.7 on 2023-04-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweet_controller", "0008_like_delete_reaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Like", "verbose_name_plural": "Likes"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_comments",
                to="tweet_controller.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_replies",
                to="tweet_controller.tweet",
            ),
        ),
    ]
