# Generated by Django 4.1.7 on 2023-05-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweet_controller", "0012_likecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreplay",
            name="replay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies_comments",
                to="tweet_controller.comment",
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to="tweet_controller.comment",
            ),
        ),
    ]
