# Generated by Django 4.1.7 on 2023-05-03 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "tweet_controller",
            "0013_alter_commentreplay_replay_alter_likecomment_comment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweet_comments",
                to="tweet_controller.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tweet_controller.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
