# Generated by Django 4.1.7 on 2023-05-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_controller', '0012_alter_commentreplay_replay_likecomment'),
        ('tweet_controller', '0014_tweet_comment_alter_comment_tweet_alter_comment_user'),
    ]

    operations = [
    ]
