# Generated by Django 4.1.7 on 2023-04-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, max_length=600, verbose_name="Website"),
        ),
    ]
