# Generated by Django 4.1.7 on 2023-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_rename_name_customuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='create_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
