# Generated by Django 4.1.7 on 2023-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_control", "0003_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verify",
            field=models.BooleanField(default=False),
        ),
    ]
