# Generated by Django 4.1.7 on 2023-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_control", "0004_customuser_is_verify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_profile_image.png",
                upload_to="user_profile/",
                verbose_name="Image",
            ),
        ),
    ]
